[package]
name = "starkveil_e2e"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"

[lib]

[cairo]
sierra-replace-ids = false
inlining-strategy = 0

[dev-dependencies]
snforge_std = "0.57.0"
assert_macros = "2.14.0"

[[target.starknet-contract]]
casm = false
casm-add-pythonic-hints = false
